"""add_wakeup_time

Revision ID: 22d972d1a417
Revises: 752225f85f32
Create Date: 2020-07-21 14:38:26.727661

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22d972d1a417"
down_revision = "752225f85f32"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sleep_records",
        sa.Column("wakeup_time", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sleep_records", "wakeup_time")
    # ### end Alembic commands ###
