"""remove chat table move language to user

Revision ID: 5f878d7571b0
Revises: 10269b12355a
Create Date: 2020-08-31 12:56:34.827694

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f878d7571b0"
down_revision = "10269b12355a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("language", sa.String(length=12), nullable=True))
    op.drop_column("users", "locale")

    # move data
    op.execute(
        "UPDATE users SET language = (SELECT c.language FROM chats c WHERE users.id = c.id)"
    )

    op.drop_index("ix_chats_id", table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "is_official",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "language", sa.VARCHAR(length=12), autoincrement=False, nullable=True
        ),
        sa.Column(
            "join_filter",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="chats_pkey"),
    )
    op.create_index("ix_chats_id", "chats", ["id"], unique=False)

    # move data
    op.execute(
        "UPDATE chats SET language = (SELECT u.language FROM users u WHERE chats.id = u.id)"
    )

    op.add_column(
        "users", sa.Column("locale", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("users", "language")
    # ### end Alembic commands ###
