"""scheduler

Revision ID: 63547cf99070
Revises: 09cc034d3174
Create Date: 2020-07-23 23:43:14.372604

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "63547cf99070"
down_revision = "09cc034d3174"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", sa.VARCHAR(length=191), nullable=False),
        sa.Column(
            "next_run_time", postgresql.DOUBLE_PRECISION(precision=53), nullable=True
        ),
        sa.Column("job_state", postgresql.BYTEA(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apscheduler_jobs_next_run_time"),
        "apscheduler_jobs",
        ["next_run_time"],
        unique=False,
    )
    op.create_table(
        "reminder_jobs",
        sa.Column("job_id", sa.VARCHAR(length=191), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["apscheduler_jobs.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reminder_jobs")
    op.drop_index(
        op.f("ix_apscheduler_jobs_next_run_time"), table_name="apscheduler_jobs"
    )
    op.drop_table("apscheduler_jobs")
    # ### end Alembic commands ###
