"""add_emoji

Revision ID: 752225f85f32
Revises: 6dd5b6ee2687
Create Date: 2020-07-19 11:25:32.939568

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "752225f85f32"
down_revision = "6dd5b6ee2687"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sleep_records", sa.Column("emoji", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sleep_records", "emoji")
    # ### end Alembic commands ###
