"""remove check wakeup

Revision ID: 8ae6b9ae2c37
Revises: 22d972d1a417
Create Date: 2020-07-21 14:41:50.965384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8ae6b9ae2c37"
down_revision = "22d972d1a417"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sleep_records", "check_wakeup")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sleep_records",
        sa.Column("check_wakeup", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
