"""add_mood

Revision ID: b8bfbb8170b6
Revises: d459222e4af3
Create Date: 2020-07-19 11:11:16.102951

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b8bfbb8170b6"
down_revision = "d459222e4af3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sleep_records", sa.Column("mood", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sleep_records", "mood")
    # ### end Alembic commands ###
