"""rename reminder jobs

Revision ID: cb71584de89d
Revises: 63547cf99070
Create Date: 2020-08-04 11:29:53.676277

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cb71584de89d"
down_revision = "63547cf99070"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminders",
        sa.Column("job_id", sa.VARCHAR(length=191), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["apscheduler_jobs.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
    )

    op.execute(
        "INSERT INTO reminders (job_id, user_id, created_at, updated_at) "
        "SELECT job_id, user_id, created_at, updated_at FROM reminder_jobs"
    )

    op.drop_table("reminder_jobs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reminder_jobs",
        sa.Column(
            "job_id", sa.VARCHAR(length=191), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["apscheduler_jobs.id"],
            name="reminder_jobs_job_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="reminder_jobs_user_id_fkey",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
    )

    op.execute(
        "INSERT INTO reminder_jobs (job_id, user_id, created_at, updated_at) "
        "SELECT job_id, user_id, created_at, updated_at FROM reminders"
    )

    op.drop_table("reminders")
    # ### end Alembic commands ###
