"""add_users_timezone

Revision ID: d459222e4af3
Revises: ea79705817e4
Create Date: 2020-07-10 11:25:09.242955

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d459222e4af3"
down_revision = "ea79705817e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("timezone", sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("UPDATE users SET timezone = '+00:00' WHERE timezone IS NULL")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "timezone")
    # ### end Alembic commands ###
