"""remove old user fields

Revision ID: ea79705817e4
Revises: ee8211c3f0fe
Create Date: 2020-07-09 16:39:26.617647

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea79705817e4"
down_revision = "ee8211c3f0fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "location")
    op.drop_column("users", "lot_limit")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "lot_limit",
            sa.INTEGER(),
            server_default=sa.text("500"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users", sa.Column("location", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
