"""rename_sleep record check wakeup

Revision ID: ee8211c3f0fe
Revises: 2d53aed10b7c
Create Date: 2020-07-09 15:38:05.809943

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee8211c3f0fe"
down_revision = "2d53aed10b7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sleep_records", sa.Column("check_wakeup", sa.Boolean(), nullable=True)
    )
    op.drop_column("sleep_records", "check")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sleep_records",
        sa.Column("check", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("sleep_records", "check_wakeup")
    # ### end Alembic commands ###
